# Generated by Django 3.2.3 on 2021-05-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_app', '0004_dojos_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='he',
            field=models.TextField(null=True),
        ),
    ]
