# Generated by Django 3.2.3 on 2021-05-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_app', '0005_dojos_he'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojos',
            name='he',
        ),
    ]
