# Generated by Django 3.2.3 on 2021-05-23 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninjas',
            name='dojo_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='koko', to='dojo_app.dojos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dojos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ninjas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
