# Generated by Django 3.2.3 on 2021-05-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_app', '0003_auto_20210523_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.TextField(default='old dojo', max_length=700),
            preserve_default=False,
        ),
    ]
